### PR TITLE
DOA-eXist Test PR v2 - Do Not Merge!  

### PR DESCRIPTION
**Pull request by windauer**
DOA-eXist Test PR v2 - Do Not Merge!

### CODE REVIEW

**Comment by joewiz** [comment]
@windauer This PR doesn't appear to be rebased from master. It still contains records such as https://github.com/HistoryAtState/pocom/blob/ed61040e31f2376375c6f0d1c30ea8f849d5df64/missions-countries/afghanistan.xml without the `<arrived>` element in every record. Compare to master version of the same file: https://github.com/HistoryAtState/pocom/blob/master/missions-countries/afghanistan.xml.

**Comment by windauer** [comment]
@joewiz I think this is not a rebase issue but a doa-exist pocom.xqm xml generation issue. I will take care of it.

**Comment by joewiz** [comment]
@windauer Ah, yes, you're right. I see how the commit diff shows the new `<arrived>` elements are being _deleted_. In that case, no rush, please just tackle this the course of addressing our request on the order of the `<arrived>` element in COM records.

**Comment by windauer** [comment]
@joewiz latest commits now always creates the <arrived> element.

**Pull request closed without merging**
